/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJPanel.java
 *
 * Created on 2009-06-04, 01:34:38
 */

package progkomp.kacperczerwonka.test;

/**
 *
 * @author karolrvn
 */
public class NewJPanel extends javax.swing.JPanel {

    /** Creates new form NewJPanel */
    public NewJPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        multiplicationTableComponent3 = new progkomp.kacperczerwonka.component.MultiplicationTableComponent();

        multiplicationTableComponent3.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        multiplicationTableComponent3.setNumbersHorizontally(15);

        javax.swing.GroupLayout multiplicationTableComponent3Layout = new javax.swing.GroupLayout(multiplicationTableComponent3);
        multiplicationTableComponent3.setLayout(multiplicationTableComponent3Layout);
        multiplicationTableComponent3Layout.setHorizontalGroup(
            multiplicationTableComponent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );
        multiplicationTableComponent3Layout.setVerticalGroup(
            multiplicationTableComponent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(multiplicationTableComponent3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(multiplicationTableComponent3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private progkomp.kacperczerwonka.component.MultiplicationTableComponent multiplicationTableComponent3;
    // End of variables declaration//GEN-END:variables

}
